name: Main workflow

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet build ./CICD/application/Apps.sln
    - run: dotnet run ./CICD/application/BenchRepo/BenchRepo.csproj

    # - name: Check installed version
    #   shell: pwsh
    #   run: |
    #     $version = & dotnet --version
    #     Write-Host "Installed version: $version"
    #     if (-not $version.StartsWith("${{ matrix.dotnet-version }}")) { throw "Unexpected version" }